services:
  mongo:
    image: mongo:8
    container_name: refurbops-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: refurbops
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: refurbops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: refurbops-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongo_data:
  redis_data:
